import exerciseData from "./components/exerciseData";

const exerciseArray: exerciseData[] = [
    //Legs
    {
      parentID: "100",
      exerciseID: '201',
      name: "RDL",
      sets: 3,
      targetReps: 12,
      weight: "Plate 30",
      restTime: "03:00",
      marked: false,
    },
    {
      parentID: "100",
      exerciseID: '202',
      name: "Leg Extension",
      sets: 3,
      targetReps: 10,
      weight: "200",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "100",
      exerciseID: '203',
      name: "Calves (Machine)",
      sets: 3,
      targetReps: 12,
      weight: "250",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "100",
      exerciseID: '204',
      name: "Seated Leg Curl (One Leg)",
      sets: 3,
      targetReps: 12,
      weight: "90",
      restTime: "03:00",
      marked: false,
    },
    {
      parentID: "100",
      exerciseID: '205',
      name: "Leg Press (Single Leg)",
      sets: 3,
      targetReps: 12,
      weight: "2 Plate + 20",
      restTime: "03:00",
      marked: false,
    },

    //Chest & Back
    {
      parentID: "101",
      exerciseID: '206',
      name: "Dumbell Incline Press",
      sets: 3,
      targetReps: 8,
      weight: "70",
      restTime: "03:00",
      marked: false,
    },
    {
      parentID: "101",
      exerciseID: '207',
      name: "Barbell Bent Over Row",
      sets: 3,
      targetReps: 10,
      weight: "Plate 20",
      restTime: "03:00",
      marked: false,
    },
    {
      parentID: "101",
      exerciseID: '208',
      name: "Chest Fly",
      sets: 3,
      targetReps: 8,
      weight: "135",
      restTime: "03:00",
      marked: false,
    },
    {
      parentID: "101",
      exerciseID: '209',
      name: "Lat Row",
      sets: 3,
      targetReps: 12,
      weight: "57.5",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "101",
      exerciseID: '210',
      name: "Iso Frontal Pulldown",
      sets: 3,
      targetReps: 12,
      weight: "2 Plates 15",
      restTime: "03:00",
      marked: false,
    },

    //Shoulders & Arms
    {
      parentID: "102",
      exerciseID: '211',
      name: "Shoulder Press",
      sets: 3,
      targetReps: 8,
      weight: "2 Plates (100)",
      restTime: "03:00",
      marked: false,
    },
    {
      parentID: "102",
      exerciseID: '212',
      name: "Tricep Push Down",
      sets: 3,
      targetReps: 12,
      weight: "62.5",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "102",
      exerciseID: '213',
      name: "Hammer Curl",
      sets: 3,
      targetReps: 12,
      weight: "62.5",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "102",
      exerciseID: '214',
      name: "Overhead Triceps Extension",
      sets: 3,
      targetReps: 12,
      weight: "60",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "102",
      exerciseID: '215',
      name: "Lateral Raise",
      sets: 3,
      targetReps: 12,
      weight: "25",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "102",
      exerciseID: '216',
      name: "Bicep Curl",
      sets: 3,
      targetReps: 12,
      weight: "30",
      restTime: "02:00",
      marked: false,
    },
    {
      parentID: "102",
      exerciseID: '217',
      name: "Reverse Curl",
      sets: 3,
      targetReps: 12,
      weight: "15",
      restTime: "02:00",
      marked: false,
    },
]
export default exerciseArray;